version: 2.1

filters_always: &filters_always
  filters:
    tags:
      only: /.*/

orbs:
  macos: circleci/macos@2
  bats: circleci/bats@1.0.0

jobs:
  lint:
    macos:
      xcode: 26.1.0
    resource_class: m4pro.medium

    steps:
      - checkout
      - run: make lint

  build:
    parameters:
      destination:
        type: string
    macos:
      xcode: 26.1.0
    resource_class: m4pro.medium
    steps:
      - checkout
      - run: xcodebuild -version
      - run: xcodebuild -scheme honeycomb-opentelemetry-swift -destination << parameters.destination >>

  tests:
    macos:
      xcode: 26.1.0
    resource_class: m4pro.medium

    steps:
      - macos/preboot-simulator:
          version: "18.6"
          platform: "iOS"
          device: "iPhone 16"
      - checkout
      - run: xcodebuild -version
      - run: xcodebuild -showsdks
      - run: xcodebuild test -scheme HoneycombTests -sdk iphonesimulator26.1 -showdestinations
      - run: xcodebuild test -scheme HoneycombTests -sdk iphonesimulator26.1 -destination 'OS=18.6,name=iPhone 16'

  smoke_tests:
    parameters:
      otel_version:
        type: string
    macos:
      xcode: 26.1.0
    resource_class: m4pro.medium

    steps:
      - attach_workspace:
          at: ./
      - macos/preboot-simulator:
          version: "18.6"
          platform: "iOS"
          device: "iPhone 16"
      - checkout
      - bats/install
      - run:
          name: What's the BATS?
          command: |
            which bats
            bats --version
      - run: xcodebuild -version
      - run:
          name: Install OTel Collector
          environment:
            COLLECTOR_VERSION: "0.111.0"
          command: |
            curl --proto '=https' --tlsv1.2 -fOL https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v${COLLECTOR_VERSION}/otelcol_${COLLECTOR_VERSION}_darwin_arm64.tar.gz
            tar -xvf otelcol_${COLLECTOR_VERSION}_darwin_arm64.tar.gz
      - run:
          name: Start OTel Collector
          command: touch ./smoke-tests/collector/data.json && ./otelcol --config=./smoke-tests/collector/otel-collector-config.yaml --set="exporters::file::path=./smoke-tests/collector/data.json"
          background: true
      - run:
          name: Start Mock Server
          working_directory: smoke-tests/mock-server
          command: npm install && npm start
          background: true
      - run:
          name: Set opentelemetry-swift version
          command: ./set-otel-version.sh << parameters.otel_version >>
      - run:
          name: Run iOS App
          command: SMOKE_TEST_DESTINATION="OS=18.6,name=iPhone 16" make ios-tests
      - run:
          name: Run Smoke Tests
          command: make smoke-bats
      - store_artifacts:
          path: smoke-tests/collector/data.json

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - lint
      - build:
          matrix:
            parameters:
              destination:
                - generic/platform=macOS
                - generic/platform=iOS
                - generic/platform=tvOS
                - generic/platform=watchOS
      - tests
      - smoke_tests:
          matrix:
            parameters:
              otel_version:
                - 2.0.2

  build:
    jobs:
      - lint:
          <<: *filters_always
      - build:
          <<: *filters_always
          matrix:
            parameters:
              destination:
                - generic/platform=macOS
                - generic/platform=iOS
                - generic/platform=tvOS
                - generic/platform=watchOS
      - tests:
          <<: *filters_always
      - smoke_tests:
          <<: *filters_always
          matrix:
            parameters:
              otel_version:
                - 2.0.2
